import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
//const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>local</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Coding</h1>
        <div className={styles.description}>
          <p> I am learning Next.js </p>
          </div>
          {/* <Image
            src={`https://dev.freelogogenerator.com/img/hero-banner.svg`}
            alt="Picture of the author"
            width={350}
            height={400}
            priority  // lazy load false 
          /> */}
          <img  src='https://dev.freelogogenerator.com/img/hero-banner.svg'
            alt="Picture of the author"/>
        
      </main>
    </>
  )
}